use crate::{issues::issue::Issue, parse::crash_report::CrashReport};

#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[derive(Debug, PartialEq, Eq)]
pub struct SuspectedModInfo {
    mod_name: String,
    mod_name_normalized: String,
    mod_version: String,
    issue_tracker: Option<String>,
}

fn find_issue_tracker_url(text: &str, index: usize) -> Option<&str> {
    for line in text.lines().skip(index + 1) {
        let line = line.strip_prefix("\t\t")?;
        if let Some(url) = line.strip_prefix("Issue tracker URL: ") {
            return Some(url);
        }
    }
    return None;
}

/// Takes in the Crash Report Head section
fn check_suspected_mod_report_head(crash_report_head: &str) -> Option<Issue> {
    // Text is generated by https://github.com/MinecraftForge/MinecraftForge/blob/ef811aebe8cfc1f8c43fe455f58156107a371bbe/src/main/java/net/minecraftforge/logging/CrashReportAnalyser.java#L65
    let (_, s) = crash_report_head.split_once("Suspected Mod:").or_else(|| crash_report_head.split_once("Suspected Mods:"))?;
    if s.starts_with(" NONE") { return None; }
    let (s, _) = s.split_once("Stacktrace:")?;

    let mut vec: Vec<SuspectedModInfo> = Vec::new();
    for (index, line) in s.lines().enumerate() {
        let indent = line.chars().take_while(|c| *c == '\t').count();
        let stripped = line.get(indent..)?.trim_ascii_end();
        if indent == 1 {
            let (mod_str, mod_version) = stripped.split_once("), Version: ")?;
            let (mod_name, mod_name_normalized) = mod_str.split_once(" (")?;            
            let issue_tracker_url = find_issue_tracker_url(s, index);

            let info = SuspectedModInfo {
                mod_name: mod_name.trim_ascii_end().to_string(),
                mod_name_normalized: mod_name_normalized.to_string(),
                mod_version: mod_version.to_string(),
                issue_tracker: issue_tracker_url.map(|s| s.to_string()),
            };
            vec.push(info);
        }
    }

    (vec.len() > 0).then_some(Issue::ForgeSuspectedMod(vec))
}

pub(crate) fn check_suspected_mod_crash_report(report: &CrashReport) -> Option<Issue> {
    let head = report.sections.get("Head")?;
    check_suspected_mod_report_head(head)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn finds_suspected_mod() {
        let crash_report = include_str!("../../parse/test_data/crash_4.log");
        let issue = check_suspected_mod_report_head(&crash_report).expect("Failed to find issue");
        let Issue::ForgeSuspectedMod(suspected_mods) = issue else { panic!("Not the right issue"); };
        let suspected_mod = &suspected_mods[0];
        assert_eq!(suspected_mod.mod_name, "Selling Bin");
        assert_eq!(suspected_mod.mod_name_normalized, "sellingbin");
        assert_eq!(suspected_mod.mod_version, "1.0.9");
        assert_eq!(suspected_mod.issue_tracker.as_ref().unwrap(), "https://github.com/bigchadguys/DailyShop/issues");
    }

    #[test]
    fn finds_multiple_suspected_mods() {
        let crash_report_fragment = r#"
-- Head --
Thread: Render thread
Suspected Mods: 
	Create (create), Version: 6.0.8
		Issue tracker URL: https://github.com/Creators-of-Create/Create/issues
		at TRANSFORMER/create@6.0.8/com.simibubi.create.foundation.blockEntity.SyncedBlockEntity.notifyUpdate(SyncedBlockEntity.java:67)

	Create: Copycats  (copycats), Version: 3.0.2 mc.1.20.1-forge
		Issue tracker URL: https://github.com/copycats-plus/copycats/issues
		at TRANSFORMER/copycats@3.0.2 mc.1.20.1-forge/com.copycatsplus.copycats.foundation.copycat.CCCopycatBlockEntity.notifyUpdate(CCCopycatBlockEntity.java:43)

	Radium (radium), Version: 0.12.4 git.26c9d8e
		Issue tracker URL: https://github.com/Reforged-Hub/radium-upstream/issues
		Mixin class: me.jellysquid.mods.lithium.mixin.world.chunk_access.WorldMixin
		Target: net.minecraft.world.level.Level
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46745_(Level.java:4536)
Stacktrace:        
"#;
        let issue = check_suspected_mod_report_head(&crash_report_fragment).expect("Failed to find issue");
        let Issue::ForgeSuspectedMod(suspected_mods) = issue else { panic!("Not the right issue"); };
        assert_eq!(suspected_mods[0].mod_name, "Create");
        assert_eq!(suspected_mods[0].mod_name_normalized, "create");
        assert_eq!(suspected_mods[0].mod_version, "6.0.8");
        assert_eq!(suspected_mods[0].issue_tracker.as_ref().unwrap(), "https://github.com/Creators-of-Create/Create/issues");
        assert_eq!(suspected_mods[1].mod_name, "Create: Copycats");
        assert_eq!(suspected_mods[1].mod_name_normalized, "copycats");
        assert_eq!(suspected_mods[1].mod_version, "3.0.2 mc.1.20.1-forge");
        assert_eq!(suspected_mods[1].issue_tracker.as_ref().unwrap(), "https://github.com/copycats-plus/copycats/issues");
        assert_eq!(suspected_mods[2].mod_name, "Radium");
        assert_eq!(suspected_mods[2].mod_name_normalized, "radium");
        assert_eq!(suspected_mods[2].mod_version, "0.12.4 git.26c9d8e");
        assert_eq!(suspected_mods[2].issue_tracker.as_ref().unwrap(), "https://github.com/Reforged-Hub/radium-upstream/issues");
    }

    #[test]
    fn suspected_is_none() {
        let crash_report_fragment = r#"
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
"#;
        let issue = check_suspected_mod_report_head(&crash_report_fragment);
        assert!(issue.is_none());
    }
}