// This information seems to be generated by https://www.baeldung.com/java-9-stackwalking-api

use crate::parse::stacktrace::model::StacktraceLine;

#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "dioxius", derive(Clone, PartialEq))]
pub struct JarPosition {
    position: usize,
    char: char,
}

#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "dioxius", derive(Clone, PartialEq))]
pub struct StacktraceLineSourceInfo {
    jar_name: String,
    jar_position: Option<JarPosition>,
    version: Option<String>,
    entries: Vec<String>,
}

impl StacktraceLine {
    pub fn extract_source_info(&self) -> Option<StacktraceLineSourceInfo> {
        parse_trace_source_info(&self.source_info)
    }
}

fn parse_trace_source_info(s: &str) -> Option<StacktraceLineSourceInfo> {
    // "~[?:?] {}" -> "?:?] {}"
    let (wo_tilde, _has_tilde) = if let Some(wo) = s.strip_prefix('~') { (wo, true) } else { (s, false) };
    let s = wo_tilde.strip_prefix('[')?;
    // "[modlauncher-11.0.5.jar#154!/:?] {}" -> {"modlauncher-11.0.5.jar#154!/:?", ""}
    let (left, entries) =  if let Some(s) = s.strip_suffix('}') {
        let (l, r) = s.split_once("] {")?;
        (l, parse_entries(r))
    }
    else {
        (s.strip_suffix(']')?, None)
    };
    let (jar, version) = left.split_once(':')?;
    if version == "" { return None; }
    let version = if version == "?" { None } else { Some(version) };
    let jar = jar.strip_suffix("!/").unwrap_or(jar);
    let (jar, jar_position) = extract_jar_pos(jar);

    let entries: Vec<String> = if let Some(vec) = entries { vec.iter().map(|e| e.to_string()).collect() } else { vec![] };

    Some(StacktraceLineSourceInfo {
        jar_name: jar.to_string(),
        jar_position: jar_position,
        version: version.map(|s| s.to_string()),
        entries: entries,
    })
}

fn parse_entries(s: &str) -> Option<Vec<&str>> {
    if s == "" { return None; }
    let entries = s.split(',').collect::<Vec<_>>();
    Some(entries)
}

fn extract_jar_pos(jar: &str) -> (&str, Option<JarPosition>) {
    // Forge logs both contain # and %, this doesn't seem to be specific to one
    let (jar, pos_str, sep) =  if let Some((l, r)) = jar.split_once('#') {
        (l, r, '#')
    }
    else if let Some((l, r)) = jar.split_once('%') {
        (l, r, '%')
    }
    else {
        return (jar, None);
    };
    let Some(pos) = pos_str.parse::<usize>().ok() else {
        return (jar, None);
    };
    return (jar, Some(JarPosition { position: pos, char: sep }));
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn various() {
        let stacktrace_info = [
            "~[client-1.21.1-20240808.144430-srg.jar#285!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sodium-extra.mixins.json:prevent_shaders.MixinGameRenderer from mod sodium_extra,pl:mixin:APP:mixins.iris.json:GameRendererAccessor from mod iris,pl:mixin:APP:mixins.iris.json:MixinGameRenderer from mod iris,pl:mixin:APP:mixins.iris.json:MixinModelViewBobbing from mod iris,pl:mixin:APP:ok_zoomer.mixins.json:GameRendererMixin from mod ok_zoomer,pl:mixin:APP:entity_model_features.mixins.json:MixinGameRenderer from mod entity_model_features,pl:mixin:APP:entity_model_features.mixins.json:accessor.Mixin_GuiEntityTester from mod entity_model_features,pl:mixin:APP:lighty.mixins.json:GameRendererAccessor from mod lighty,pl:mixin:APP:dynamic_fps-common.mixins.json:GameRendererMixin from mod dynamic_fps,pl:mixin:APP:sodium-common.mixins.json:features.gui.hooks.console.GameRendererMixin from mod sodium,pl:mixin:APP:elytratrims-client.mixins.json:GameRendererMixin from mod elytratrims,pl:mixin:APP:cubes-without-borders.mixins.json:GameRendererMixin from mod cubes_without_borders,pl:mixin:APP:ponder-common.mixins.json:client.accessor.GameRendererAccessor from mod ponder,pl:mixin:APP:freecam-common.mixins.json:GameRendererMixin from mod freecam,pl:mixin:APP:create.mixins.json:client.GameRendererMixin from mod create,pl:mixin:APP:mixins.iris.json:MixinGameRenderer_NightVisionCompat from mod iris,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}",
            "~[?:?] {}",
            "~[?:?] {re:mixin}",
            "~[loader-4.0.42.jar#149!/:4.0] {}",
            "[modlauncher-11.0.5.jar#154!/:?] {}",
            "[ForgeWrapper-prism-2025-10-07.jar:prism-2025-10-07] {}",
            "~[destroy-1.20.1-0.1.3-all.jar#166!/:0.1.3] {re:mixin,re:classloading}",
            "~[loader-47.2.2.jar:47.2] {}",
            "~[modlauncher-10.0.9.jar:?] {}",
            "~[unusual_delight-4.4.jar#375!/:?] {re:classloading}",
            "~[minecraft-1.20.1-client.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:smoothboot.mixins.json:client.MainMixin,pl:mixin:A,pl:runtimedistcleaner:A}",
            "~[fmlloader-1.20.1-47.4.0.jar:?] {}",
            "~[modlauncher-10.0.9.jar:?] {}",
            "~[bootstraplauncher-1.1.2.jar:?] {}",
            "~[forge-1.20.1-47.4.8-universal.jar%23699!/:?] {re:classloading}",
            "~[client-1.20.1-20230612.114412-srg.jar%23694!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}",
            "~[mixin-0.8.5.jar:0.8.5 Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}",
            "~[forge-1.20.1-47.4.8-universal.jar%23697!/:?] {re:classloading}",
            "~[client-1.20.1-20230612.114412-srg.jar%23692!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}",
            "~[forge-1.20.1-47.4.0-universal.jar#255!/:?] {re:classloading}",
            "~[client-1.20.1-20230612.114412-srg.jar#250!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alexscaves.mixins.json:client.MinecraftMixin,pl:mixin:APP:xaeroworldmap.mixins.json:MixinMinecraftClient,pl:mixin:APP:xaeroworldmap.forge.mixins.json:MixinForgeMinecraftClient,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientAccessor,pl:mixin:APP:bettercombat.mixins.json:client.MinecraftClientInject,pl:mixin:APP:xaerohud.mixins.json:MixinMinecraftClient,pl:mixin:APP:mixins.irons_spellbooks.json:MinecraftMixin,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}",
            "~[forge-1.20.1-47.4.0-universal.jar#255!/:?] {re:classloading}",
            "~[client-1.20.1-20230612.114412-srg.jar#250!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}",
            "~[minecraft-1.20.1-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}",
            "~[loader-4.0.42.jar%23161!/:4.0] {}",
            "[ForgeWrapper-prism-2025-10-07.jar:prism-2025-10-07] {}",
            "[NewLaunch.jar:?] {}",
            "~[fmlloader-1.20.1-47.4.0.jar:?] {}",
            "~[client-1.21.1-20240808.144430-srg.jar%23291!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:APP:lithostitched.mixins.json:common.PlacedFeatureAccessor from mod lithostitched,pl:mixin:A,pl:connector_pre_launch:A}",
            "~[DistantHorizons-2.3.6-b-1.21.1-fabric-neoforge.jar#211!/:?] {re:mixin,re:classloading}",
            "~[[1.20.1-Forge] Hybrid Aquatic 1.5.2 Hotfix.jar#371!/:1.5.2] {re:mixin,re:classloading}",
            "~[ShoulderSurfing-Forge-1.21.10-4.17.1.jar!/:1.21.10-4.17.1]",
            "~[forge-1.21.10-60.1.0-client.jar!/:?]",
        ];
        for info in stacktrace_info {
            parse_trace_source_info(info).expect("Failed to parse");
        }
    }

    #[test]
    fn extract_jar() {
        let text = "~[unusual_delight-4.4.jar#375!/:?] {re:classloading}";
        let info = parse_trace_source_info(text).expect("Failed to parse");
        assert_eq!(info.jar_name, "unusual_delight-4.4.jar");
        let jar_pos = info.jar_position.unwrap();
        assert_eq!(jar_pos.position, 375);
        assert_eq!(jar_pos.char, '#');
        assert_eq!(info.entries, vec!["re:classloading"]);
    }

    #[test]
    fn extract_version() {
        let text = "~[[1.20.1-Forge] Hybrid Aquatic 1.5.2 Hotfix.jar#371!/:1.5.2] {re:mixin,re:classloading}";
        let info = parse_trace_source_info(text).expect("Failed to parse");
        assert_eq!(info.jar_name, "[1.20.1-Forge] Hybrid Aquatic 1.5.2 Hotfix.jar");
        assert_eq!(info.version.unwrap(), "1.5.2");
        let jar_pos = info.jar_position.unwrap();
        assert_eq!(jar_pos.position, 371);
        assert_eq!(jar_pos.char, '#');
        assert_eq!(info.entries, vec!["re:mixin", "re:classloading"]);
    }
}